In [1]:
import pandas as pd

In [2]:
# LDA
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis

In [3]:
# Split the train and test
from sklearn.model_selection import train_test_split

In [4]:
# standardScaler
from sklearn.preprocessing import StandardScaler

In [5]:
# Machine learning algorithms for categorical 

from sklearn.linear_model import LogisticRegression # this name is logisticRegression but its support the classification problems
from sklearn.svm import SVC # Support vector classifier
from sklearn.naive_bayes import GaussianNB # Gaussian naive bayes
from sklearn.neighbors import KNeighborsClassifier # KNN neighbors classifier
from sklearn.tree import DecisionTreeClassifier # Decision Tree Classifier
from sklearn.ensemble import RandomForestClassifier # Random forest classifier

# load the dataSet

In [6]:
dataset = pd.read_csv('CKD.csv')

In [7]:
dataset.head()

,age,bp,sg,al,su,rbc,pc,pcc,ba,bgr,...,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
0,2.0,76.459948,c,3.0,0.0,normal,abnormal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,yes,no,yes
1,3.0,76.459948,c,2.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,34.000000,12300.000000,4.705597,no,no,no,yes,poor,no,yes
2,4.0,76.459948,a,1.0,0.0,normal,normal,notpresent,notpresent,99.000000,...,34.000000,8408.191126,4.705597,no,no,no,yes,poor,no,yes
3,5.0,76.459948,d,1.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,poor,yes,yes
4,5.0,50.000000,c,0.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,36.000000,12400.000000,4.705597,no,no,no,yes,poor,no,yes

In [8]:
dataset['classification'].value_counts()

yes    249
no     150
Name: classification, dtype: int64

In [9]:
dataset = pd.get_dummies(dataset, drop_first = True)

In [10]:
dataset.head()

,age,bp,al,su,bgr,bu,sc,sod,pot,hrmo,...,pc_normal,pcc_present,ba_present,htn_yes,dm_yes,cad_yes,appet_yes,pe_yes,ane_yes,classification_yes
0,2.0,76.459948,3.0,0.0,148.112676,57.482105,3.077356,137.528754,4.627244,12.518156,...,0,0,0,0,0,0,1,1,0,1
1,3.0,76.459948,2.0,0.0,148.112676,22.000000,0.700000,137.528754,4.627244,10.700000,...,1,0,0,0,0,0,1,0,0,1
2,4.0,76.459948,1.0,0.0,99.000000,23.000000,0.600000,138.000000,4.400000,12.000000,...,1,0,0,0,0,0,1,0,0,1
3,5.0,76.459948,1.0,0.0,148.112676,16.000000,0.700000,138.000000,3.200000,8.100000,...,1,0,0,0,0,0,1,0,1,1
4,5.0,50.000000,0.0,0.0,148.112676,25.000000,0.600000,137.528754,4.627244,11.800000,...,1,0,0,0,0,0,1,0,0,1

In [11]:
independent = dataset.drop('classification_yes', 1)

In [12]:
independent.head()

,age,bp,al,su,bgr,bu,sc,sod,pot,hrmo,...,rbc_normal,pc_normal,pcc_present,ba_present,htn_yes,dm_yes,cad_yes,appet_yes,pe_yes,ane_yes
0,2.0,76.459948,3.0,0.0,148.112676,57.482105,3.077356,137.528754,4.627244,12.518156,...,1,0,0,0,0,0,0,1,1,0
1,3.0,76.459948,2.0,0.0,148.112676,22.000000,0.700000,137.528754,4.627244,10.700000,...,1,1,0,0,0,0,0,1,0,0
2,4.0,76.459948,1.0,0.0,99.000000,23.000000,0.600000,138.000000,4.400000,12.000000,...,1,1,0,0,0,0,0,1,0,0
3,5.0,76.459948,1.0,0.0,148.112676,16.000000,0.700000,138.000000,3.200000,8.100000,...,1,1,0,0,0,0,0,1,0,1
4,5.0,50.000000,0.0,0.0,148.112676,25.000000,0.600000,137.528754,4.627244,11.800000,...,1,1,0,0,0,0,0,1,0,0

In [13]:
dependent = dataset['classification_yes']
dependent.head()

0    1
1    1
2    1
3    1
4    1
Name: classification_yes, dtype: uint8

# Linear discriminant analysis

In [14]:
def Linear_Discriminant_Analysis(independent,dependent,n):
    lda = LinearDiscriminantAnalysis(n_components=1)
    fit1 = lda.fit_transform(independent, dependent)
    Lda_features = lda.transform(independent)
    return Lda_features

# split the train and test

In [15]:
# Splitting the dataset into the Training set and Test set
def SplitTrainTest(independent, dependent):
    X_train, X_test, y_train, y_test = train_test_split(independent, dependent, test_size = 0.25, random_state = 0)
    return X_train, X_test, y_train, y_test

# Standard scaler

In [16]:
def Standard_Scaler(X_train, X_test):
    sc = StandardScaler()
    X_train = sc.fit_transform(X_train)
    X_test = sc.transform(X_test)
    return X_train, X_test

# Algorithm predication accuracy

In [17]:
def cm_prediction(classifier, X_test):
    Y_Pred = classifier.predict(X_test)
    
    from sklearn.metrics import confusion_matrix
    cm = confusion_matrix(y_test, Y_Pred)    
    
    from sklearn.metrics import accuracy_score 
    from sklearn.metrics import classification_report 
    
    Accuracy=accuracy_score(y_test, Y_Pred )
    
    report = classification_report(y_test, Y_Pred)
    return classifier, Accuracy, report, X_test, y_test, cm

# Model creation

In [18]:
# logistic function
def logistic(X_train, y_train, X_test):
    classifier = LogisticRegression(random_state = 0)
    classifier.fit(X_train, y_train)
    classifier, Accuracy, report, X_test, y_test, cm = cm_prediction(classifier, X_test)
    return classifier, Accuracy, report, X_test, y_test, cm

# support vector classifier (svc)
def SVM_linear(X_train, y_train, X_test):
    classifier = SVC(kernel = 'linear', random_state = 0)
    classifier.fit(X_train, y_train)
    classifier, Accuracy, report, X_test, y_test, cm = cm_prediction(classifier, X_test)
    return classifier, Accuracy, report, X_test, y_test, cm

# support vector classifier (svc)
def SVM_NL(X_train, y_train, X_test):
    classifier = SVC(kernel = 'rbf', random_state = 0)
    classifier.fit(X_train, y_train)
    classifier, Accuracy, report, X_test, y_test, cm = cm_prediction(classifier, X_test)
    return classifier, Accuracy, report, X_test, y_test, cm

# Navie bayes
def Navie(X_train, y_train, X_test):
    classifier = GaussianNB()
    classifier.fit(X_train, y_train)
    classifier, Accuracy, report, X_test, y_test, cm = cm_prediction(classifier, X_test)
    return classifier, Accuracy, report, X_test, y_test, cm

# K nearest neighbour
def knn(X_train, y_train, X_test):
    classifier = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)
    classifier.fit(X_train, y_train)
    classifier, Accuracy, report, X_test, y_test, cm = cm_prediction(classifier, X_test)
    return classifier, Accuracy, report, X_test, y_test, cm


# Decision tree
def Decision(X_train, y_train, X_test):
    classifier = DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
    classifier.fit(X_train, y_train)
    classifier, Accuracy, report, X_test, y_test, cm = cm_prediction(classifier, X_test)
    return classifier, Accuracy, report, X_test, y_test, cm

# Random forest
def random(X_train, y_train, X_test):
    classifier = RandomForestClassifier(n_estimators = 10, criterion = 'entropy', random_state = 0)
    classifier.fit(X_train, y_train)
    classifier, Accuracy, report, X_test, y_test, cm = cm_prediction(classifier, X_test)
    return classifier, Accuracy, report, X_test, y_test, cm

In [19]:
def selectk_Classification(acclog,accsvml,accsvmnl,accnav,accknn,accdes,accrf): 
    
    dataframe=pd.DataFrame(index=['KernelPCA'],columns=['Logistic','SVMl','SVMnl','Navie','KNN','Decision','Random'])
    for number,idex in enumerate(dataframe.index):      
        dataframe['Logistic'][idex]=acclog[number]       
        dataframe['SVMl'][idex]=accsvml[number]
        dataframe['SVMnl'][idex]=accsvmnl[number]
        dataframe['Navie'][idex]=accnav[number]
        dataframe['KNN'][idex]=accknn[number]
        dataframe['Decision'][idex]=accdes[number]
        dataframe['Random'][idex]=accrf[number]
    return dataframe

In [29]:
LdA=Linear_Discriminant_Analysis(independent,dependent,2)
acclog=[]
accsvml=[]
accsvmnl=[]
accnav=[]
accknn=[]
accdes=[]
accrf=[]

In [26]:
LdA

array([[ 0.81981835],
       [ 1.56847644],
       [-0.52064042],
       [ 1.93238122],
       [ 0.79282681],
       [ 1.82662484],
       [-0.11256948],
       [-1.01518225],
       [-0.39830217],
       [-0.99480451],
       [ 0.16703827],
       [ 1.05291541],
       [-2.06936146],
       [ 1.30691042],
       [ 1.0161603 ],
       [-3.0185253 ],
       [-0.33846521],
       [ 0.71157414],
       [-2.49260119],
       [-0.60269757],
       [-1.49255882],
       [-2.28295831],
       [-1.69137383],
       [ 0.35645975],
       [ 1.90723877],
       [-2.1471307 ],
       [-3.30618975],
       [-2.25928344],
       [-2.8327288 ],
       [-2.03335993],
       [ 1.71000954],
       [-2.93691686],
       [-2.55074692],
       [-1.11305331],
       [-2.45881865],
       [-1.79014666],
       [-1.42410924],
       [-0.05456152],
       [-0.92287816],
       [-1.15772315],
       [-3.69356759],
       [-1.80061365],
       [-2.50764912],
       [-1.63941818],
       [ 0.68242445],
       [-1.51497615],
       [-2.02208412],
       [-2.37023552],
       [-0.81088436],
       [-2.1503289 ],
       [-2.62474253],
       [ 2.11852443],
       [-2.41949888],
       [-2.49452978],
       [ 1.000105  ],
       [-3.30212941],
       [-1.81022106],
       [-2.48823466],
       [-2.2971062 ],
       [-2.33222799],
       [ 1.40365193],
       [ 0.8475226 ],
       [-0.63483069],
       [-0.82403349],
       [ 1.0887866 ],
       [-2.18137575],
       [-1.49705389],
       [-2.62150898],
       [-3.41997495],
       [ 2.45024297],
       [ 1.86032453],
       [-2.15167477],
       [-2.00340499],
       [-2.71509092],
       [-2.63238311],
       [ 0.62439901],
       [-2.81551766],
       [ 0.47592591],
       [-3.10263019],
       [-2.03772426],
       [-0.24812207],
       [-1.65861909],
       [-1.53324126],
       [ 1.63702612],
       [-1.87248066],
       [-2.64121114],
       [-1.75545819],
       [ 2.40223462],
       [ 2.88666277],
       [-2.13628647],
       [-0.90645276],
       [ 1.26574357],
       [ 1.19105959],
       [-2.43286084],
       [-2.24266439],
       [-3.29539456],
       [ 2.1893708 ],
       [-0.22784199],
       [-1.44643354],
       [-1.6016432 ],
       [-2.41453477],
       [-3.30369614],
       [-0.08946481],
       [-2.25573589],
       [-2.65257561],
       [-0.86778281],
       [-3.49368661],
       [-2.19611023],
       [-0.07318176],
       [-2.0804533 ],
       [-3.260783  ],
       [-2.08310368],
       [-2.50782779],
       [-2.16363677],
       [ 0.66001142],
       [ 0.32809644],
       [ 2.41001675],
       [ 0.87743521],
       [ 2.56931287],
       [-0.41775   ],
       [ 1.34979394],
       [-2.91324377],
       [-2.11797248],
       [-1.88961546],
       [ 1.50268268],
       [ 2.15577209],
       [ 2.66492384],
       [ 1.33387224],
       [ 2.30259948],
       [ 0.99706535],
       [-2.85661527],
       [-1.30574177],
       [-3.2529924 ],
       [ 0.73248709],
       [-0.12768633],
       [ 1.96877806],
       [-0.00773866],
       [ 2.10170074],
       [-0.95254071],
       [-1.441574  ],
       [-2.47170872],
       [-1.42423133],
       [-2.07873024],
       [-1.35004965],
       [ 1.54418939],
       [-0.56390723],
       [ 1.17397961],
       [ 1.55691762],
       [ 1.91213564],
       [ 1.34472324],
       [ 2.06754386],
       [ 2.43676717],
       [-2.15040938],
       [-1.86982964],
       [-3.27761169],
       [ 3.60099386],
       [-2.34518911],
       [ 2.64692499],
       [-0.69029596],
       [ 2.62050163],
       [ 2.0404229 ],
       [ 1.71026379],
       [ 1.03555987],
       [-0.39944582],
       [ 1.91838066],
       [ 1.02921583],
       [-1.67389141],
       [-2.02450243],
       [-1.38539403],
       [ 1.00755678],
       [ 0.95336531],
       [-2.05689201],
       [-2.48087419],
       [-2.03134408],
       [ 2.26839727],
       [ 3.54777437],
       [-2.16247533],
       [-2.02319752],
       [-2.58131166],
       [ 1.50553552],
       [ 1.1659806 ],
       [ 1.25690765],
       [ 1.41009565],
       [-2.88812101],
       [ 3.45769206],
       [ 1.93552329],
       [ 3.25313526],
       [ 0.12106633],
       [-0.24514451],
       [-0.79551737],
       [ 2.55627088],
       [ 0.98359747],
       [-1.38676485],
       [-2.0903679 ],
       [ 1.30793645],
       [ 0.51425705],
       [ 2.64459316],
       [ 1.4414813 ],
       [ 3.47010214],
       [ 2.14887402],
       [-1.83397263],
       [-1.04669212],
       [-2.7104749 ],
       [-2.59082548],
       [-2.55228859],
       [-2.1458687 ],
       [ 2.64200585],
       [ 1.83297973],
       [ 0.46535019],
       [ 0.2197781 ],
       [ 1.78334414],
       [ 3.19944622],
       [ 4.52197225],
       [-2.266096  ],
       [-2.88471185],
       [-2.23079434],
       [ 2.79434364],
       [ 1.70241824],
       [ 2.15550058],
       [ 1.29610584],
       [-2.55677071],
       [-2.33036859],
       [-1.85498631],
       [-1.89167819],
       [ 2.61700594],
       [-1.84101362],
       [-1.80826345],
       [-3.12834473],
       [-2.85062376],
       [ 1.71242729],
       [ 2.66779957],
       [ 2.99501986],
       [ 0.77608768],
       [ 2.44351198],
       [ 3.74754642],
       [ 2.50921677],
       [ 1.93360354],
       [-2.14608179],
       [-2.10348106],
       [ 2.2261995 ],
       [-0.30930259],
       [ 3.11252783],
       [ 1.14766958],
       [ 2.74755953],
       [ 1.71008247],
       [ 0.48302338],
       [ 1.48383296],
       [ 3.15917799],
       [-0.4923493 ],
       [ 1.31949194],
       [ 0.40566187],
       [ 2.65516971],
       [-0.44147271],
       [ 0.90451457],
       [-2.12254048],
       [-2.15793145],
       [-1.66182763],
       [-2.47383791],
       [ 3.39505823],
       [-0.1832877 ],
       [ 2.54096066],
       [ 1.1131611 ],
       [ 1.05720706],
       [-0.40743264],
       [ 0.05800392],
       [-3.3568129 ],
       [-2.12444228],
       [ 2.52589811],
       [ 1.48890532],
       [ 1.28417247],
       [ 1.17994842],
       [-0.34197075],
       [ 1.71571643],
       [ 1.39095907],
       [-0.49507486],
       [-2.71762779],
       [-3.13949743],
       [ 3.33722216],
       [ 0.78268044],
       [ 1.00797056],
       [ 1.1685915 ],
       [ 1.23819813],
       [-2.07507546],
       [-2.43050754],
       [ 2.25238895],
       [ 3.30561949],
       [ 1.20363886],
       [ 0.40325448],
       [ 3.79029308],
       [ 2.30025379],
       [-1.79241397],
       [-1.63229547],
       [ 1.0807542 ],
       [ 0.89439048],
       [ 1.24034961],
       [ 2.95727186],
       [ 0.23650065],
       [ 2.80742376],
       [ 2.20358904],
       [ 0.61114237],
       [ 2.56160538],
       [ 0.88390748],
       [ 2.53691842],
       [ 2.95906228],
       [ 2.00009287],
       [ 1.14878995],
       [ 2.66755066],
       [-1.64573938],
       [-2.7958337 ],
       [ 0.92638986],
       [ 2.44580529],
       [ 0.61480658],
       [-2.20427437],
       [-1.93709863],
       [-0.43422252],
       [-0.26869031],
       [ 0.73547904],
       [ 1.93821168],
       [ 2.69530443],
       [ 0.40067562],
       [-3.43434073],
       [ 1.13706838],
       [ 3.32212882],
       [ 0.95929904],
       [ 4.02828632],
       [-0.09521934],
       [ 0.65988541],
       [ 3.15939515],
       [-3.53132807],
       [ 1.56146322],
       [ 0.09915253],
       [ 0.29086058],
       [ 0.83289613],
       [ 2.2586995 ],
       [-2.38299318],
       [ 0.67291669],
       [ 0.49231589],
       [ 2.5806123 ],
       [ 1.96197077],
       [ 2.13717244],
       [ 1.39626585],
       [ 2.20171743],
       [-2.30763913],
       [-2.02919432],
       [ 1.98723352],
       [ 0.82399509],
       [ 2.77118436],
       [ 1.30348252],
       [ 1.69928808],
       [-1.8547829 ],
       [-2.69393335],
       [-3.28371462],
       [ 1.159746  ],
       [-0.54631957],
       [ 1.09800896],
       [-0.65199569],
       [ 0.63251627],
       [ 0.77909483],
       [-2.06731352],
       [ 1.89873342],
       [ 2.54759177],
       [ 0.92413364],
       [ 3.25194878],
       [ 0.34980293],
       [ 1.7384897 ],
       [-2.0872066 ],
       [-2.37273476],
       [ 2.10560562],
       [-0.09632953],
       [-2.93817125],
       [ 2.46102539],
       [-0.55023477],
       [-0.12269198],
       [-1.72608013],
       [-1.12249609],
       [ 1.99358444],
       [ 2.32881831],
       [-0.05094879],
       [ 1.71501979],
       [ 0.97732097],
       [ 0.64376818],
       [-3.0660933 ],
       [ 1.52999615],
       [ 2.02890021],
       [-2.05056829],
       [-2.33488068],
       [ 0.9698439 ],
       [ 1.42259305],
       [ 1.54254311],
       [-0.275876  ],
       [-0.23114975],
       [ 3.84407814],
       [ 1.5842342 ],
       [ 1.39111965],
       [-0.59759196],
       [ 2.38837037],
       [ 3.14842633],
       [ 1.26352395],
       [-2.32625144]])

In [27]:
X_train, X_test, y_train, y_test=SplitTrainTest(LdA,dependent)   
    
        
classifier,Accuracy,report,X_test,y_test,cm=logistic(X_train,y_train,X_test)
acclog.append(Accuracy)

classifier,Accuracy,report,X_test,y_test,cm=SVM_linear(X_train,y_train,X_test)  
accsvml.append(Accuracy)
    
classifier,Accuracy,report,X_test,y_test,cm=SVM_NL(X_train,y_train,X_test)  
accsvmnl.append(Accuracy)

classifier,Accuracy,report,X_test,y_test,cm=Navie(X_train,y_train,X_test)  
accnav.append(Accuracy)
    
classifier,Accuracy,report,X_test,y_test,cm=knn(X_train,y_train,X_test)  
accknn.append(Accuracy)
    
classifier,Accuracy,report,X_test,y_test,cm=Decision(X_train,y_train,X_test)  
accdes.append(Accuracy)
    
classifier,Accuracy,report,X_test,y_test,cm=random(X_train,y_train,X_test)  
accrf.append(Accuracy)
    
result=selectk_Classification(acclog,accsvml,accsvmnl,accnav,accknn,accdes,accrf)

C:\Users\Administrator\Anaconda3\envs\aiml\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Administrator\Anaconda3\envs\aiml\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
C:\Users\Administrator\Anaconda3\envs\aiml\lib\site-packages\sklearn\neighbors\base.py:441: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  old_joblib = LooseVersion(joblib_version) < LooseVersion('0.12')
C:\Users\Administrator\Anaconda3\envs\aiml\lib\site-packages\sklearn\neighbors\base.py:441: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  old_joblib = LooseVersion(joblib_version) < LooseVersion('0.12')
C:\Users\Administrator\Anaconda3\envs\aiml\lib\site-packages\sklearn\utils\fixes.py:230: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  if _joblib.__version__ >= LooseVersion('0.12'):
C:\Users\Administrator\Anaconda3\envs\aiml\lib\site-packages\sklearn\utils\fixes.py:230: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  if _joblib.__version__ >= LooseVersion('0.12'):

In [24]:
result
#2

          Logistic  SVMl SVMnl Navie   KNN Decision Random
KernelPCA     0.99  0.98  0.98  0.98  0.98     0.99   0.99